<?php
$cl_units = new units();
$cl_units->set_unitfactor("0.65","0.94355");

$cl_units->add_unit("Spearman","unit_spear");
$cl_units->set_woodprice("50");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("10");
$cl_units->set_bhprice("1");
$cl_units->set_time("1000");
$cl_units->set_att("50","1.045");
$cl_units->set_def("100","1.045");
$cl_units->set_defcav("200","1.045");
$cl_units->set_defarcher("300","1.045");
$cl_units->set_speed("720");
$cl_units->set_booty("25");
$cl_units->set_needed(array());
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array("barracks"=>"1"));
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("def");
$cl_units->set_description("The Spearman is a basic defensive unit and is especially effective against cavalry.");

$cl_units->add_unit("Swordsman","unit_sword");
$cl_units->set_woodprice("30");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("70");
$cl_units->set_bhprice("1");
$cl_units->set_time("1500");
$cl_units->set_att("100","1.045");
$cl_units->set_def("300","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("900");
$cl_units->set_booty("15");
$cl_units->set_needed(array("barracks"=>"1","smith"=>"1"));
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("def");
$cl_units->set_description("The Swordsman is a strong defensive unit, particularly useful against infantry.");

$cl_units->add_unit("Axeman","unit_axe");
$cl_units->set_woodprice("60");
$cl_units->set_stoneprice("30");
$cl_units->set_ironprice("40");
$cl_units->set_bhprice("1");
$cl_units->set_time("1250");
$cl_units->set_att("350","1.0455");
$cl_units->set_def("70","1.045");
$cl_units->set_defcav("50","1.045");
$cl_units->set_defarcher("50","1.045");
$cl_units->set_speed("720");
$cl_units->set_booty("10");
$cl_units->set_needed(array("barracks"=>"1","smith"=>"2"));
$cl_units->set_recruit_in("barracks");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("A");
$cl_units->set_attType("off");
$cl_units->set_description("The Axeman is a powerful offensive unit made for aggressive assaults.");

if($config['archers']){
	$cl_units->add_unit("Archer","unit_archer");
	$cl_units->set_woodprice("100");
	$cl_units->set_stoneprice("30");
	$cl_units->set_ironprice("60");
	$cl_units->set_bhprice("1");
	$cl_units->set_time("1750");
	$cl_units->set_att("150","1.045");
	$cl_units->set_def("400","1.045");
	$cl_units->set_defcav("150","1.045");
	$cl_units->set_defarcher("100","1.045");
	$cl_units->set_speed("720");
	$cl_units->set_booty("10");
	$cl_units->set_needed(array("barracks"=>"5","smith"=>"5"));
	$cl_units->set_recruit_in("barracks");
	$cl_units->set_specials(array());
	$cl_units->set_group("archer");
	$cl_units->set_col("A");
	$cl_units->set_attType("def");
	$cl_units->set_description("Archers are deadly at range and provide solid defensive support.");
}

$cl_units->add_unit("Scout","unit_spy");
$cl_units->set_woodprice("50");
$cl_units->set_stoneprice("50");
$cl_units->set_ironprice("20");
$cl_units->set_bhprice("2");
$cl_units->set_time("1250");
$cl_units->set_att("1","1.045");
$cl_units->set_def("10","1.045");
$cl_units->set_defcav("5","1.045");
$cl_units->set_defarcher("7","1.045");
$cl_units->set_speed("360");
$cl_units->set_booty("0");
$cl_units->set_needed(array("stable"=>1));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("spy");
$cl_units->set_description("Scouts gather information about enemy villages. The more you send, the better the report.");

$cl_units->add_unit("Light Cavalry","unit_light");
$cl_units->set_woodprice("125");
$cl_units->set_stoneprice("100");
$cl_units->set_ironprice("250");
$cl_units->set_bhprice("4");
$cl_units->set_time("2400");
$cl_units->set_att("900","1.045");
$cl_units->set_def("200","1.045");
$cl_units->set_defcav("300","1.045");
$cl_units->set_defarcher("300","1.045");
$cl_units->set_speed("390");
$cl_units->set_booty("80");
$cl_units->set_needed(array("stable"=>3));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("off");
$cl_units->set_description("Light Cavalry is fast and ideal for raids and surprise attacks.");

if($config['archers']){
	$cl_units->add_unit("Mounted Archer","unit_marcher");
	$cl_units->set_woodprice("250");
	$cl_units->set_stoneprice("100");
	$cl_units->set_ironprice("150 ");
	$cl_units->set_bhprice("5");
	$cl_units->set_time("1250");
	$cl_units->set_att("120","1.045");
	$cl_units->set_def("40","1.045");
	$cl_units->set_defcav("30","1.045");
	$cl_units->set_defarcher("50","1.045");
	$cl_units->set_speed("600");
	$cl_units->set_booty("50");
	$cl_units->set_needed(array("stable"=>"5" ));
	$cl_units->set_recruit_in("stable");
	$cl_units->set_specials(array(""));
	$cl_units->set_group("cav");
	$cl_units->set_col("B");
	$cl_units->set_description("Mounted Archers are especially useful against enemy archers hiding behind the wall.");
}

$cl_units->add_unit("Heavy Cavalry","unit_heavy");
$cl_units->set_woodprice("200");
$cl_units->set_stoneprice("150");
$cl_units->set_ironprice("600");
$cl_units->set_bhprice("6");
$cl_units->set_time("3600");
$cl_units->set_att("600","1.045");
$cl_units->set_def("1500","1.045");
$cl_units->set_defcav("1000","1.045");
$cl_units->set_defarcher("1000","1.045");
$cl_units->set_speed("450");
$cl_units->set_booty("50");
$cl_units->set_needed(array("stable"=>"10","smith"=>"15"));
$cl_units->set_recruit_in("stable");
$cl_units->set_specials(array());
$cl_units->set_group("cav");
$cl_units->set_col("B");
$cl_units->set_attType("def");
$cl_units->set_description("Heavy Cavalry is the elite of your army, combining solid armor with strong defensive power.");

$cl_units->add_unit("Ram","unit_ram");
$cl_units->set_woodprice("300");
$cl_units->set_stoneprice("200");
$cl_units->set_ironprice("200");
$cl_units->set_bhprice("5");
$cl_units->set_time("1250");
$cl_units->set_att("100","1.045");
$cl_units->set_def("100","1.045");
$cl_units->set_defcav("200","1.045");
$cl_units->set_defarcher("20","1.045");
$cl_units->set_speed("1200");
$cl_units->set_booty("0");
$cl_units->set_needed(array("garage"=>"1"));
$cl_units->set_recruit_in("garage");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("C");
$cl_units->set_attType("off");
$cl_units->set_description("The Ram helps break enemy walls during attacks.");

$cl_units->add_unit("Catapult","unit_catapult");
$cl_units->set_woodprice("320");
$cl_units->set_stoneprice("400");
$cl_units->set_ironprice("100");
$cl_units->set_bhprice("8");
$cl_units->set_time("1250");
$cl_units->set_att("500","1.045");
$cl_units->set_def("400","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("1440");
$cl_units->set_booty("0");
$cl_units->set_needed(array("garage"=>"2","smith"=>"12"));
$cl_units->set_recruit_in("garage");
$cl_units->set_specials(array());
$cl_units->set_group("foot");
$cl_units->set_col("C");
$cl_units->set_attType("undefined");
$cl_units->set_description("Catapults are used to destroy enemy buildings from a distance.");

$cl_units->add_unit("Paladin","unit_knight");
$cl_units->set_woodprice("20");
$cl_units->set_stoneprice("20");
$cl_units->set_ironprice("40");
$cl_units->set_bhprice("10");
$cl_units->set_time("34424");
$cl_units->set_att("150","1.045");
$cl_units->set_def("250","1.045");
$cl_units->set_defcav("400","1.045");
$cl_units->set_defarcher("150","1.045");
$cl_units->set_speed("400");
$cl_units->set_booty("100");
$cl_units->set_needed(array());
$cl_units->set_recruit_in("statue");
$cl_units->set_specials(array("no_investigate"));
$cl_units->set_group("cav");
$cl_units->set_col("D");
$cl_units->set_attType("undefined");
$cl_units->set_description("The Paladin protects your village and allies. Each player can have only one.");

$cl_units->add_unit("Nobleman","unit_snob");
if($config['ag_style'] == 2){
  $cl_units->set_woodprice("40000");
  $cl_units->set_stoneprice("50000");
  $cl_units->set_ironprice("50000");
}else{
  $cl_units->set_woodprice("28000");
  $cl_units->set_stoneprice("30000");
  $cl_units->set_ironprice("25000");
}
$cl_units->set_bhprice("100");
$cl_units->set_time("12500");
$cl_units->set_att("100","1.045");
$cl_units->set_def("300","1.045");
$cl_units->set_defcav("100","1.045");
$cl_units->set_defarcher("200","1.045");
$cl_units->set_speed("1800");
$cl_units->set_booty("0");
$cl_units->set_needed(array("main"=>"20","smith"=>"20","market"=>"10"));
$cl_units->set_recruit_in("snob");
$cl_units->set_specials(array("no_investigate"));
$cl_units->set_group("foot");
$cl_units->set_col("D");
$cl_units->set_attType("undefined");
$cl_units->set_description("The Nobleman lowers the loyalty of enemy villages and allows them to be conquered.");
?>